[package]
name = "havenfs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.4"
serde = "1.0.166"
serde_derive = "1.0.126"
thiserror = "1.0" 
chrono = "0.4.26"